// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MJBase.proto

package packet.mj;

public final class MJBase {
  private MJBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code packet.mj.GameOperType}
   */
  public enum GameOperType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GameOperStartSyn = 7001;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    GameOperStartSyn(0, 7001),
    /**
     * <code>GameOperHandCardSyn = 7002;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    GameOperHandCardSyn(1, 7002),
    /**
     * <code>GameOperPublicInfoSyn = 7003;</code>
     *
     * <pre>
     *公共信息
     * </pre>
     */
    GameOperPublicInfoSyn(2, 7003),
    /**
     * <code>GameOperPlayerHuSyn = 7004;</code>
     *
     * <pre>
     *公共信息
     * </pre>
     */
    GameOperPlayerHuSyn(3, 7004),
    /**
     * <code>GameOperPlayerActionNotify = 7005;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    GameOperPlayerActionNotify(4, 7005),
    /**
     * <code>GameOperActorSyn = 7006;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    GameOperActorSyn(5, 7006),
    /**
     * <code>GameOperPlayerActionSyn = 7007;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(吃、碰、听、出、吃听、碰听)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    GameOperPlayerActionSyn(6, 7007),
    /**
     * <code>GameOperBaoChangeSyn = 7008;</code>
     *
     * <pre>
     *换宝 
     * </pre>
     */
    GameOperBaoChangeSyn(7, 7008),
    /**
     * <code>GameOperReNofity = 7009;</code>
     *
     * <pre>
     *重新提醒操作,调试用
     * </pre>
     */
    GameOperReNofity(8, 7009),
    /**
     * <code>GameOperFinalSettleSyn = 7010;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    GameOperFinalSettleSyn(9, 7010),
    /**
     * <code>DDZGameOperStartSyn = 8001;</code>
     *
     * <pre>
     *===================================poker==========================================
     * </pre>
     */
    DDZGameOperStartSyn(10, 8001),
    /**
     * <code>DDZGameOperHandCardSyn = 8002;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    DDZGameOperHandCardSyn(11, 8002),
    /**
     * <code>DDZGameOperPublicInfoSyn = 8003;</code>
     *
     * <pre>
     *剩下的三张牌
     * </pre>
     */
    DDZGameOperPublicInfoSyn(12, 8003),
    /**
     * <code>DDZGameOperPlayerActionNotify = 8004;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    DDZGameOperPlayerActionNotify(13, 8004),
    /**
     * <code>DDZGameOperActorSyn = 8005;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    DDZGameOperActorSyn(14, 8005),
    /**
     * <code>DDZGameOperPlayerActionSyn = 8006;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(出,过,抢地主,加倍等)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    DDZGameOperPlayerActionSyn(15, 8006),
    /**
     * <code>DDZGameOperPlayerHuSyn = 8007;</code>
     *
     * <pre>
     *单局结算
     * </pre>
     */
    DDZGameOperPlayerHuSyn(16, 8007),
    /**
     * <code>DDZGameOperFinalSettleSyn = 8008;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    DDZGameOperFinalSettleSyn(17, 8008),
    /**
     * <code>ZJHGameOperStartSyn = 8009;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    ZJHGameOperStartSyn(18, 8009),
    /**
     * <code>ZJHGameOperHandCardSyn = 8010;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    ZJHGameOperHandCardSyn(19, 8010),
    /**
     * <code>ZJHGameOperPublicInfoSyn = 8011;</code>
     *
     * <pre>
     *剩下的三张牌
     * </pre>
     */
    ZJHGameOperPublicInfoSyn(20, 8011),
    /**
     * <code>ZJHGameOperPlayerActionNotify = 8012;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    ZJHGameOperPlayerActionNotify(21, 8012),
    /**
     * <code>ZJHGameOperActorSyn = 8013;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    ZJHGameOperActorSyn(22, 8013),
    /**
     * <code>ZJHGameOperPlayerActionSyn = 8014;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(出,过,抢地主,加倍等)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    ZJHGameOperPlayerActionSyn(23, 8014),
    /**
     * <code>ZJHGameOperPlayerHuSyn = 8015;</code>
     *
     * <pre>
     *单局结算
     * </pre>
     */
    ZJHGameOperPlayerHuSyn(24, 8015),
    /**
     * <code>ZJHGameOperFinalSettleSyn = 8016;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    ZJHGameOperFinalSettleSyn(25, 8016),
    /**
     * <code>JACKGameOperStartSyn = 8017;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    JACKGameOperStartSyn(26, 8017),
    /**
     * <code>JACKGameOperHandCardSyn = 8018;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    JACKGameOperHandCardSyn(27, 8018),
    /**
     * <code>JACKGameOperPublicInfoSyn = 8019;</code>
     *
     * <pre>
     *剩下的三张牌
     * </pre>
     */
    JACKGameOperPublicInfoSyn(28, 8019),
    /**
     * <code>JACKGameOperPlayerActionNotify = 8020;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    JACKGameOperPlayerActionNotify(29, 8020),
    /**
     * <code>JACKGameOperActorSyn = 8021;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    JACKGameOperActorSyn(30, 8021),
    /**
     * <code>JACKGameOperPlayerActionSyn = 8022;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(出,过,抢地主,加倍等)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    JACKGameOperPlayerActionSyn(31, 8022),
    /**
     * <code>JACKGameOperPlayerHuSyn = 8023;</code>
     *
     * <pre>
     *单局结算
     * </pre>
     */
    JACKGameOperPlayerHuSyn(32, 8023),
    /**
     * <code>JACKGameOperFinalSettleSyn = 8024;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    JACKGameOperFinalSettleSyn(33, 8024),
    /**
     * <code>NNGameOperStartSyn = 8025;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    NNGameOperStartSyn(34, 8025),
    /**
     * <code>NNGameOperHandCardSyn = 8026;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    NNGameOperHandCardSyn(35, 8026),
    /**
     * <code>NNGameOperPublicInfoSyn = 8027;</code>
     *
     * <pre>
     *剩下的三张牌
     * </pre>
     */
    NNGameOperPublicInfoSyn(36, 8027),
    /**
     * <code>NNGameOperPlayerActionNotify = 8028;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    NNGameOperPlayerActionNotify(37, 8028),
    /**
     * <code>NNGameOperActorSyn = 8029;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    NNGameOperActorSyn(38, 8029),
    /**
     * <code>NNGameOperPlayerActionSyn = 8030;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(出,过,抢地主,加倍等)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    NNGameOperPlayerActionSyn(39, 8030),
    /**
     * <code>NNGameOperPlayerHuSyn = 8031;</code>
     *
     * <pre>
     *单局结算
     * </pre>
     */
    NNGameOperPlayerHuSyn(40, 8031),
    /**
     * <code>NNGameOperFinalSettleSyn = 8032;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    NNGameOperFinalSettleSyn(41, 8032),
    /**
     * <code>ErBaGameOperStartSyn = 8033;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    ErBaGameOperStartSyn(42, 8033),
    /**
     * <code>ErBaGameOperHandCardSyn = 8034;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    ErBaGameOperHandCardSyn(43, 8034),
    /**
     * <code>ErBaGameOperPublicInfoSyn = 8035;</code>
     *
     * <pre>
     *剩下的三张牌
     * </pre>
     */
    ErBaGameOperPublicInfoSyn(44, 8035),
    /**
     * <code>ErBaGameOperPlayerActionNotify = 8036;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    ErBaGameOperPlayerActionNotify(45, 8036),
    /**
     * <code>ErBaGameOperActorSyn = 8037;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    ErBaGameOperActorSyn(46, 8037),
    /**
     * <code>ErBaGameOperPlayerActionSyn = 8038;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(出,过,抢地主,加倍等)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    ErBaGameOperPlayerActionSyn(47, 8038),
    /**
     * <code>ErBaGameOperPlayerHuSyn = 8039;</code>
     *
     * <pre>
     *单局结算
     * </pre>
     */
    ErBaGameOperPlayerHuSyn(48, 8039),
    /**
     * <code>ErBaGameOperFinalSettleSyn = 8040;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    ErBaGameOperFinalSettleSyn(49, 8040),
    ;

    /**
     * <code>GameOperStartSyn = 7001;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    public static final int GameOperStartSyn_VALUE = 7001;
    /**
     * <code>GameOperHandCardSyn = 7002;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    public static final int GameOperHandCardSyn_VALUE = 7002;
    /**
     * <code>GameOperPublicInfoSyn = 7003;</code>
     *
     * <pre>
     *公共信息
     * </pre>
     */
    public static final int GameOperPublicInfoSyn_VALUE = 7003;
    /**
     * <code>GameOperPlayerHuSyn = 7004;</code>
     *
     * <pre>
     *公共信息
     * </pre>
     */
    public static final int GameOperPlayerHuSyn_VALUE = 7004;
    /**
     * <code>GameOperPlayerActionNotify = 7005;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    public static final int GameOperPlayerActionNotify_VALUE = 7005;
    /**
     * <code>GameOperActorSyn = 7006;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    public static final int GameOperActorSyn_VALUE = 7006;
    /**
     * <code>GameOperPlayerActionSyn = 7007;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(吃、碰、听、出、吃听、碰听)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    public static final int GameOperPlayerActionSyn_VALUE = 7007;
    /**
     * <code>GameOperBaoChangeSyn = 7008;</code>
     *
     * <pre>
     *换宝 
     * </pre>
     */
    public static final int GameOperBaoChangeSyn_VALUE = 7008;
    /**
     * <code>GameOperReNofity = 7009;</code>
     *
     * <pre>
     *重新提醒操作,调试用
     * </pre>
     */
    public static final int GameOperReNofity_VALUE = 7009;
    /**
     * <code>GameOperFinalSettleSyn = 7010;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    public static final int GameOperFinalSettleSyn_VALUE = 7010;
    /**
     * <code>DDZGameOperStartSyn = 8001;</code>
     *
     * <pre>
     *===================================poker==========================================
     * </pre>
     */
    public static final int DDZGameOperStartSyn_VALUE = 8001;
    /**
     * <code>DDZGameOperHandCardSyn = 8002;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    public static final int DDZGameOperHandCardSyn_VALUE = 8002;
    /**
     * <code>DDZGameOperPublicInfoSyn = 8003;</code>
     *
     * <pre>
     *剩下的三张牌
     * </pre>
     */
    public static final int DDZGameOperPublicInfoSyn_VALUE = 8003;
    /**
     * <code>DDZGameOperPlayerActionNotify = 8004;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    public static final int DDZGameOperPlayerActionNotify_VALUE = 8004;
    /**
     * <code>DDZGameOperActorSyn = 8005;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    public static final int DDZGameOperActorSyn_VALUE = 8005;
    /**
     * <code>DDZGameOperPlayerActionSyn = 8006;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(出,过,抢地主,加倍等)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    public static final int DDZGameOperPlayerActionSyn_VALUE = 8006;
    /**
     * <code>DDZGameOperPlayerHuSyn = 8007;</code>
     *
     * <pre>
     *单局结算
     * </pre>
     */
    public static final int DDZGameOperPlayerHuSyn_VALUE = 8007;
    /**
     * <code>DDZGameOperFinalSettleSyn = 8008;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    public static final int DDZGameOperFinalSettleSyn_VALUE = 8008;
    /**
     * <code>ZJHGameOperStartSyn = 8009;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    public static final int ZJHGameOperStartSyn_VALUE = 8009;
    /**
     * <code>ZJHGameOperHandCardSyn = 8010;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    public static final int ZJHGameOperHandCardSyn_VALUE = 8010;
    /**
     * <code>ZJHGameOperPublicInfoSyn = 8011;</code>
     *
     * <pre>
     *剩下的三张牌
     * </pre>
     */
    public static final int ZJHGameOperPublicInfoSyn_VALUE = 8011;
    /**
     * <code>ZJHGameOperPlayerActionNotify = 8012;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    public static final int ZJHGameOperPlayerActionNotify_VALUE = 8012;
    /**
     * <code>ZJHGameOperActorSyn = 8013;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    public static final int ZJHGameOperActorSyn_VALUE = 8013;
    /**
     * <code>ZJHGameOperPlayerActionSyn = 8014;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(出,过,抢地主,加倍等)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    public static final int ZJHGameOperPlayerActionSyn_VALUE = 8014;
    /**
     * <code>ZJHGameOperPlayerHuSyn = 8015;</code>
     *
     * <pre>
     *单局结算
     * </pre>
     */
    public static final int ZJHGameOperPlayerHuSyn_VALUE = 8015;
    /**
     * <code>ZJHGameOperFinalSettleSyn = 8016;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    public static final int ZJHGameOperFinalSettleSyn_VALUE = 8016;
    /**
     * <code>JACKGameOperStartSyn = 8017;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    public static final int JACKGameOperStartSyn_VALUE = 8017;
    /**
     * <code>JACKGameOperHandCardSyn = 8018;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    public static final int JACKGameOperHandCardSyn_VALUE = 8018;
    /**
     * <code>JACKGameOperPublicInfoSyn = 8019;</code>
     *
     * <pre>
     *剩下的三张牌
     * </pre>
     */
    public static final int JACKGameOperPublicInfoSyn_VALUE = 8019;
    /**
     * <code>JACKGameOperPlayerActionNotify = 8020;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    public static final int JACKGameOperPlayerActionNotify_VALUE = 8020;
    /**
     * <code>JACKGameOperActorSyn = 8021;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    public static final int JACKGameOperActorSyn_VALUE = 8021;
    /**
     * <code>JACKGameOperPlayerActionSyn = 8022;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(出,过,抢地主,加倍等)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    public static final int JACKGameOperPlayerActionSyn_VALUE = 8022;
    /**
     * <code>JACKGameOperPlayerHuSyn = 8023;</code>
     *
     * <pre>
     *单局结算
     * </pre>
     */
    public static final int JACKGameOperPlayerHuSyn_VALUE = 8023;
    /**
     * <code>JACKGameOperFinalSettleSyn = 8024;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    public static final int JACKGameOperFinalSettleSyn_VALUE = 8024;
    /**
     * <code>NNGameOperStartSyn = 8025;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    public static final int NNGameOperStartSyn_VALUE = 8025;
    /**
     * <code>NNGameOperHandCardSyn = 8026;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    public static final int NNGameOperHandCardSyn_VALUE = 8026;
    /**
     * <code>NNGameOperPublicInfoSyn = 8027;</code>
     *
     * <pre>
     *剩下的三张牌
     * </pre>
     */
    public static final int NNGameOperPublicInfoSyn_VALUE = 8027;
    /**
     * <code>NNGameOperPlayerActionNotify = 8028;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    public static final int NNGameOperPlayerActionNotify_VALUE = 8028;
    /**
     * <code>NNGameOperActorSyn = 8029;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    public static final int NNGameOperActorSyn_VALUE = 8029;
    /**
     * <code>NNGameOperPlayerActionSyn = 8030;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(出,过,抢地主,加倍等)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    public static final int NNGameOperPlayerActionSyn_VALUE = 8030;
    /**
     * <code>NNGameOperPlayerHuSyn = 8031;</code>
     *
     * <pre>
     *单局结算
     * </pre>
     */
    public static final int NNGameOperPlayerHuSyn_VALUE = 8031;
    /**
     * <code>NNGameOperFinalSettleSyn = 8032;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    public static final int NNGameOperFinalSettleSyn_VALUE = 8032;
    /**
     * <code>ErBaGameOperStartSyn = 8033;</code>
     *
     * <pre>
     *游戏开始
     * </pre>
     */
    public static final int ErBaGameOperStartSyn_VALUE = 8033;
    /**
     * <code>ErBaGameOperHandCardSyn = 8034;</code>
     *
     * <pre>
     *手牌
     * </pre>
     */
    public static final int ErBaGameOperHandCardSyn_VALUE = 8034;
    /**
     * <code>ErBaGameOperPublicInfoSyn = 8035;</code>
     *
     * <pre>
     *剩下的三张牌
     * </pre>
     */
    public static final int ErBaGameOperPublicInfoSyn_VALUE = 8035;
    /**
     * <code>ErBaGameOperPlayerActionNotify = 8036;</code>
     *
     * <pre>
     *通知玩家操作
     * </pre>
     */
    public static final int ErBaGameOperPlayerActionNotify_VALUE = 8036;
    /**
     * <code>ErBaGameOperActorSyn = 8037;</code>
     *
     * <pre>
     *广播当前正在操作的玩家
     * </pre>
     */
    public static final int ErBaGameOperActorSyn_VALUE = 8037;
    /**
     * <code>ErBaGameOperPlayerActionSyn = 8038;</code>
     *
     * <pre>
     *客户端请求服务器某个操作(出,过,抢地主,加倍等)，服务器向其他人同步玩家的这个操作也是用这个编码
     * </pre>
     */
    public static final int ErBaGameOperPlayerActionSyn_VALUE = 8038;
    /**
     * <code>ErBaGameOperPlayerHuSyn = 8039;</code>
     *
     * <pre>
     *单局结算
     * </pre>
     */
    public static final int ErBaGameOperPlayerHuSyn_VALUE = 8039;
    /**
     * <code>ErBaGameOperFinalSettleSyn = 8040;</code>
     *
     * <pre>
     *总结算
     * </pre>
     */
    public static final int ErBaGameOperFinalSettleSyn_VALUE = 8040;


    public final int getNumber() { return value; }

    public static GameOperType valueOf(int value) {
      switch (value) {
        case 7001: return GameOperStartSyn;
        case 7002: return GameOperHandCardSyn;
        case 7003: return GameOperPublicInfoSyn;
        case 7004: return GameOperPlayerHuSyn;
        case 7005: return GameOperPlayerActionNotify;
        case 7006: return GameOperActorSyn;
        case 7007: return GameOperPlayerActionSyn;
        case 7008: return GameOperBaoChangeSyn;
        case 7009: return GameOperReNofity;
        case 7010: return GameOperFinalSettleSyn;
        case 8001: return DDZGameOperStartSyn;
        case 8002: return DDZGameOperHandCardSyn;
        case 8003: return DDZGameOperPublicInfoSyn;
        case 8004: return DDZGameOperPlayerActionNotify;
        case 8005: return DDZGameOperActorSyn;
        case 8006: return DDZGameOperPlayerActionSyn;
        case 8007: return DDZGameOperPlayerHuSyn;
        case 8008: return DDZGameOperFinalSettleSyn;
        case 8009: return ZJHGameOperStartSyn;
        case 8010: return ZJHGameOperHandCardSyn;
        case 8011: return ZJHGameOperPublicInfoSyn;
        case 8012: return ZJHGameOperPlayerActionNotify;
        case 8013: return ZJHGameOperActorSyn;
        case 8014: return ZJHGameOperPlayerActionSyn;
        case 8015: return ZJHGameOperPlayerHuSyn;
        case 8016: return ZJHGameOperFinalSettleSyn;
        case 8017: return JACKGameOperStartSyn;
        case 8018: return JACKGameOperHandCardSyn;
        case 8019: return JACKGameOperPublicInfoSyn;
        case 8020: return JACKGameOperPlayerActionNotify;
        case 8021: return JACKGameOperActorSyn;
        case 8022: return JACKGameOperPlayerActionSyn;
        case 8023: return JACKGameOperPlayerHuSyn;
        case 8024: return JACKGameOperFinalSettleSyn;
        case 8025: return NNGameOperStartSyn;
        case 8026: return NNGameOperHandCardSyn;
        case 8027: return NNGameOperPublicInfoSyn;
        case 8028: return NNGameOperPlayerActionNotify;
        case 8029: return NNGameOperActorSyn;
        case 8030: return NNGameOperPlayerActionSyn;
        case 8031: return NNGameOperPlayerHuSyn;
        case 8032: return NNGameOperFinalSettleSyn;
        case 8033: return ErBaGameOperStartSyn;
        case 8034: return ErBaGameOperHandCardSyn;
        case 8035: return ErBaGameOperPublicInfoSyn;
        case 8036: return ErBaGameOperPlayerActionNotify;
        case 8037: return ErBaGameOperActorSyn;
        case 8038: return ErBaGameOperPlayerActionSyn;
        case 8039: return ErBaGameOperPlayerHuSyn;
        case 8040: return ErBaGameOperFinalSettleSyn;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameOperType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameOperType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameOperType>() {
            public GameOperType findValueByNumber(int number) {
              return GameOperType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return packet.mj.MJBase.getDescriptor().getEnumTypes().get(0);
    }

    private static final GameOperType[] VALUES = values();

    public static GameOperType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private GameOperType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:packet.mj.GameOperType)
  }

  public interface GameOperationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .packet.mj.GameOperType operType = 1;
    /**
     * <code>required .packet.mj.GameOperType operType = 1;</code>
     *
     * <pre>
     *业务类型
     * </pre>
     */
    boolean hasOperType();
    /**
     * <code>required .packet.mj.GameOperType operType = 1;</code>
     *
     * <pre>
     *业务类型
     * </pre>
     */
    packet.mj.MJBase.GameOperType getOperType();

    // optional bytes content = 2;
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
     * </pre>
     */
    com.google.protobuf.ByteString getContent();

    // optional sint32 type = 3;
    /**
     * <code>optional sint32 type = 3;</code>
     *
     * <pre>
     *0:正常游戏，1:重连或重返游戏(客户端会清空之前的操作队列)
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional sint32 type = 3;</code>
     *
     * <pre>
     *0:正常游戏，1:重连或重返游戏(客户端会清空之前的操作队列)
     * </pre>
     */
    int getType();
  }
  /**
   * Protobuf type {@code packet.mj.GameOperation}
   */
  public static final class GameOperation extends
      com.google.protobuf.GeneratedMessage
      implements GameOperationOrBuilder {
    // Use GameOperation.newBuilder() to construct.
    private GameOperation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameOperation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameOperation defaultInstance;
    public static GameOperation getDefaultInstance() {
      return defaultInstance;
    }

    public GameOperation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameOperation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              packet.mj.MJBase.GameOperType value = packet.mj.MJBase.GameOperType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                operType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readSInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return packet.mj.MJBase.internal_static_packet_mj_GameOperation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return packet.mj.MJBase.internal_static_packet_mj_GameOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packet.mj.MJBase.GameOperation.class, packet.mj.MJBase.GameOperation.Builder.class);
    }

    public static com.google.protobuf.Parser<GameOperation> PARSER =
        new com.google.protobuf.AbstractParser<GameOperation>() {
      public GameOperation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameOperation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameOperation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .packet.mj.GameOperType operType = 1;
    public static final int OPERTYPE_FIELD_NUMBER = 1;
    private packet.mj.MJBase.GameOperType operType_;
    /**
     * <code>required .packet.mj.GameOperType operType = 1;</code>
     *
     * <pre>
     *业务类型
     * </pre>
     */
    public boolean hasOperType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .packet.mj.GameOperType operType = 1;</code>
     *
     * <pre>
     *业务类型
     * </pre>
     */
    public packet.mj.MJBase.GameOperType getOperType() {
      return operType_;
    }

    // optional bytes content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
     * </pre>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    // optional sint32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>optional sint32 type = 3;</code>
     *
     * <pre>
     *0:正常游戏，1:重连或重返游戏(客户端会清空之前的操作队列)
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional sint32 type = 3;</code>
     *
     * <pre>
     *0:正常游戏，1:重连或重返游戏(客户端会清空之前的操作队列)
     * </pre>
     */
    public int getType() {
      return type_;
    }

    private void initFields() {
      operType_ = packet.mj.MJBase.GameOperType.GameOperStartSyn;
      content_ = com.google.protobuf.ByteString.EMPTY;
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOperType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, operType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, content_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, type_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static packet.mj.MJBase.GameOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static packet.mj.MJBase.GameOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static packet.mj.MJBase.GameOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static packet.mj.MJBase.GameOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(packet.mj.MJBase.GameOperation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packet.mj.GameOperation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements packet.mj.MJBase.GameOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return packet.mj.MJBase.internal_static_packet_mj_GameOperation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return packet.mj.MJBase.internal_static_packet_mj_GameOperation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                packet.mj.MJBase.GameOperation.class, packet.mj.MJBase.GameOperation.Builder.class);
      }

      // Construct using packet.mj.MJBase.GameOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        operType_ = packet.mj.MJBase.GameOperType.GameOperStartSyn;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return packet.mj.MJBase.internal_static_packet_mj_GameOperation_descriptor;
      }

      public packet.mj.MJBase.GameOperation getDefaultInstanceForType() {
        return packet.mj.MJBase.GameOperation.getDefaultInstance();
      }

      public packet.mj.MJBase.GameOperation build() {
        packet.mj.MJBase.GameOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public packet.mj.MJBase.GameOperation buildPartial() {
        packet.mj.MJBase.GameOperation result = new packet.mj.MJBase.GameOperation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operType_ = operType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof packet.mj.MJBase.GameOperation) {
          return mergeFrom((packet.mj.MJBase.GameOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(packet.mj.MJBase.GameOperation other) {
        if (other == packet.mj.MJBase.GameOperation.getDefaultInstance()) return this;
        if (other.hasOperType()) {
          setOperType(other.getOperType());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOperType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        packet.mj.MJBase.GameOperation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (packet.mj.MJBase.GameOperation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .packet.mj.GameOperType operType = 1;
      private packet.mj.MJBase.GameOperType operType_ = packet.mj.MJBase.GameOperType.GameOperStartSyn;
      /**
       * <code>required .packet.mj.GameOperType operType = 1;</code>
       *
       * <pre>
       *业务类型
       * </pre>
       */
      public boolean hasOperType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .packet.mj.GameOperType operType = 1;</code>
       *
       * <pre>
       *业务类型
       * </pre>
       */
      public packet.mj.MJBase.GameOperType getOperType() {
        return operType_;
      }
      /**
       * <code>required .packet.mj.GameOperType operType = 1;</code>
       *
       * <pre>
       *业务类型
       * </pre>
       */
      public Builder setOperType(packet.mj.MJBase.GameOperType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        operType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .packet.mj.GameOperType operType = 1;</code>
       *
       * <pre>
       *业务类型
       * </pre>
       */
      public Builder clearOperType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operType_ = packet.mj.MJBase.GameOperType.GameOperStartSyn;
        onChanged();
        return this;
      }

      // optional bytes content = 2;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
       * </pre>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
       * </pre>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       *业务数据,对应的是MJ.proto里面所有的GameOperXXX的数据结构之一
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // optional sint32 type = 3;
      private int type_ ;
      /**
       * <code>optional sint32 type = 3;</code>
       *
       * <pre>
       *0:正常游戏，1:重连或重返游戏(客户端会清空之前的操作队列)
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional sint32 type = 3;</code>
       *
       * <pre>
       *0:正常游戏，1:重连或重返游戏(客户端会清空之前的操作队列)
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional sint32 type = 3;</code>
       *
       * <pre>
       *0:正常游戏，1:重连或重返游戏(客户端会清空之前的操作队列)
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 type = 3;</code>
       *
       * <pre>
       *0:正常游戏，1:重连或重返游戏(客户端会清空之前的操作队列)
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:packet.mj.GameOperation)
    }

    static {
      defaultInstance = new GameOperation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:packet.mj.GameOperation)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_packet_mj_GameOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_packet_mj_GameOperation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014MJBase.proto\022\tpacket.mj\"Y\n\rGameOperati" +
      "on\022)\n\010operType\030\001 \002(\0162\027.packet.mj.GameOpe" +
      "rType\022\017\n\007content\030\002 \001(\014\022\014\n\004type\030\003 \001(\021*\334\013\n" +
      "\014GameOperType\022\025\n\020GameOperStartSyn\020\3316\022\030\n\023" +
      "GameOperHandCardSyn\020\3326\022\032\n\025GameOperPublic" +
      "InfoSyn\020\3336\022\030\n\023GameOperPlayerHuSyn\020\3346\022\037\n\032" +
      "GameOperPlayerActionNotify\020\3356\022\025\n\020GameOpe" +
      "rActorSyn\020\3366\022\034\n\027GameOperPlayerActionSyn\020" +
      "\3376\022\031\n\024GameOperBaoChangeSyn\020\3406\022\025\n\020GameOpe" +
      "rReNofity\020\3416\022\033\n\026GameOperFinalSettleSyn\020\342",
      "6\022\030\n\023DDZGameOperStartSyn\020\301>\022\033\n\026DDZGameOp" +
      "erHandCardSyn\020\302>\022\035\n\030DDZGameOperPublicInf" +
      "oSyn\020\303>\022\"\n\035DDZGameOperPlayerActionNotify" +
      "\020\304>\022\030\n\023DDZGameOperActorSyn\020\305>\022\037\n\032DDZGame" +
      "OperPlayerActionSyn\020\306>\022\033\n\026DDZGameOperPla" +
      "yerHuSyn\020\307>\022\036\n\031DDZGameOperFinalSettleSyn" +
      "\020\310>\022\030\n\023ZJHGameOperStartSyn\020\311>\022\033\n\026ZJHGame" +
      "OperHandCardSyn\020\312>\022\035\n\030ZJHGameOperPublicI" +
      "nfoSyn\020\313>\022\"\n\035ZJHGameOperPlayerActionNoti" +
      "fy\020\314>\022\030\n\023ZJHGameOperActorSyn\020\315>\022\037\n\032ZJHGa",
      "meOperPlayerActionSyn\020\316>\022\033\n\026ZJHGameOperP" +
      "layerHuSyn\020\317>\022\036\n\031ZJHGameOperFinalSettleS" +
      "yn\020\320>\022\031\n\024JACKGameOperStartSyn\020\321>\022\034\n\027JACK" +
      "GameOperHandCardSyn\020\322>\022\036\n\031JACKGameOperPu" +
      "blicInfoSyn\020\323>\022#\n\036JACKGameOperPlayerActi" +
      "onNotify\020\324>\022\031\n\024JACKGameOperActorSyn\020\325>\022 " +
      "\n\033JACKGameOperPlayerActionSyn\020\326>\022\034\n\027JACK" +
      "GameOperPlayerHuSyn\020\327>\022\037\n\032JACKGameOperFi" +
      "nalSettleSyn\020\330>\022\027\n\022NNGameOperStartSyn\020\331>" +
      "\022\032\n\025NNGameOperHandCardSyn\020\332>\022\034\n\027NNGameOp",
      "erPublicInfoSyn\020\333>\022!\n\034NNGameOperPlayerAc" +
      "tionNotify\020\334>\022\027\n\022NNGameOperActorSyn\020\335>\022\036" +
      "\n\031NNGameOperPlayerActionSyn\020\336>\022\032\n\025NNGame" +
      "OperPlayerHuSyn\020\337>\022\035\n\030NNGameOperFinalSet" +
      "tleSyn\020\340>\022\031\n\024ErBaGameOperStartSyn\020\341>\022\034\n\027" +
      "ErBaGameOperHandCardSyn\020\342>\022\036\n\031ErBaGameOp" +
      "erPublicInfoSyn\020\343>\022#\n\036ErBaGameOperPlayer" +
      "ActionNotify\020\344>\022\031\n\024ErBaGameOperActorSyn\020" +
      "\345>\022 \n\033ErBaGameOperPlayerActionSyn\020\346>\022\034\n\027" +
      "ErBaGameOperPlayerHuSyn\020\347>\022\037\n\032ErBaGameOp",
      "erFinalSettleSyn\020\350>"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_packet_mj_GameOperation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_packet_mj_GameOperation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_packet_mj_GameOperation_descriptor,
              new java.lang.String[] { "OperType", "Content", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
